# Generated by Django 4.0.4 on 2022-06-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='pending', max_length=150),
        ),
    ]
